version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      DB_HOST: ec2-52-91-43-195.compute-1.amazonaws.com
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    ports:
      - "5432:5432"
