version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      DB_HOST: db
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
      DB_NAME: your_db_name
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
